### ISSUE TITLE
Max number of lines per function and characters per line  wrong

### ISSUE THREAD

**Issue by jackgdll** [lucasmrdt/epitech-coding-style-checker#3]
Functions that are 20 lines long show up as 21 and same for characters per line

**Comment by 1t3x** [comment]
Are you sure? I've just tested and I don't encounter this problem.

**Comment by lucasmrdt** [comment]
can you provide us a reproducible example?

**Comment by jackgdll** [comment]
`void test(void)
{
    0;
    1;
    2;
    3;
    4;
    5;
    6;
    7;
    8;
    9;
    10;
    11;
    12;
    13;
    14;
    15;
    16;
    17;
    18;
    19;
    20;
}`
This function is valid in the moulinette but not on the coding style checker.
I am aware that there are actually 21 lines in the function but the error seems to be in the moulinette, not the extention.
I can't seem to reproduce the error for the 80 characters per line, maybe it was patched.

**Comment by lucasmrdt** [comment]
I advised you to write your issue here (https://github.com/ronanboiteau/NormEZ), it’s the program that the extension use under the hood. The issue probably comes from him.
