### ISSUE TITLE
It is not working 

### ISSUE THREAD

**Issue by charbelhani3** [lucasmrdt/epitech-coding-style-checker#7]
Hello i hope you are having a great day,
I installed the other day this extension for the piscine.  It worked 2 days ago but after i installed a python extension for my vscode, the coding style option is not working on my c projects anymore. Would you please help me?
Thank you in advance,
charbel
![Screenshot (1)](https://user-images.githubusercontent.com/71591493/93710102-47d96980-fb44-11ea-8819-4bd1373a4871.png)

**Comment by lucasmrdt** [comment]
Hi, yes this extension currently only works when you've opened a workspace. Simply open a C file is not currently implemented. Feel free to add this to the current extension for future use.
