### ISSUE TITLE
++

### ISSUE THREAD

**Issue by tbellicha** [lucasmrdt/epitech-coding-style-checker#8]
Il y a une "erreur" lorsque l'on fait size++; par exemple, car il trouve qu'il manque un espace autour du ++ :p

**Comment by lucasmrdt** [comment]
peux-tu me donner l'ensemble du code source utilisé pour que je puisse reproduire l'erreur de mon côté. De manière générale les erreurs de coding style sont la cause d'erreur de [NormEZ](https://github.com/ronanboiteau/NormEZ) qui est le programme utilisé par l'extension.

**Comment by tbellicha** [comment]
![image](https://user-images.githubusercontent.com/72006230/101776704-5a1dd080-3abf-11eb-9a8c-ff847d8572bc.png)

**Comment by lucasmrdt** [comment]
En effet le checker [NormEZ](https://github.com/ronanboiteau/NormEZ) n'accepte pas les nombres avant un `++`, je t'invite donc à faire une PR sur le repository de [NormEZ](https://github.com/ronanboiteau/NormEZ) par rapport à [cette ligne](https://github.com/ronanboiteau/NormEZ/blob/e4ecb65b97306b16b0231ebc0a9da0cd57894f5f/NormEZ.rb#L588) et après validation je mettrais à jour l'extension avec le fix.
